import React from "react";
import { useEffect, useState, useRef } from "react";
import { useParams } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import html2pdf from "html2pdf.js";
import { askLecture, getLecture } from "../api/lectures";

export default function LecturePage() {
  const { lectureId } = useParams();
  const [data, setData] = useState(null);
  const [question, setQuestion] = useState("");
  const [isDownloading, setIsDownloading] = useState(false);
  const notesRef = useRef(null);

  async function load() {
    setData(await getLecture(lectureId));
  }

  useEffect(() => {
    load();
  }, [lectureId]);

  async function ask(e) {
    e.preventDefault();
    const chatThread = await askLecture(lectureId, question);
    setData({ ...data, chatThread });
    setQuestion("");
  }

  // Build PDF HTML content
  function buildPDFHTML(lectureData) {
    const structuredNotes = lectureData.lecture.structuredNotes || {};
    const notes = structuredNotes.headings || [];

    let html = `
      <div style="padding:40px;font-family:Arial,sans-serif;color:#1e293b;max-width:800px;margin:0 auto;">
        <h1 style="font-size:28px;color:#1e293b;margin-bottom:8px;border-bottom:3px solid #2563eb;padding-bottom:12px;">
          ${lectureData.lecture.title || "Lecture Notes"}
        </h1>
        <p style="color:#64748b;font-size:14px;margin-bottom:24px;">
          ${lectureData.lecture.courseTag || "Untagged"} | ${new Date(lectureData.lecture.createdAt).toLocaleDateString()}
        </p>
    `;

    if (structuredNotes.summary) {
      html += `
        <div style="margin-bottom:24px;background:#f8fafc;padding:16px;border-radius:8px;border-left:4px solid #2563eb;">
          <h2 style="font-size:18px;color:#2563eb;margin-bottom:8px;">📚 Summary</h2>
          <p style="line-height:1.6;margin:0;">${structuredNotes.summary}</p>
        </div>
      `;
    }

    if (structuredNotes.learningObjectives?.length > 0) {
      html += `
        <div style="margin-bottom:24px;">
          <h2 style="font-size:18px;color:#2563eb;margin-bottom:8px;">🎯 Learning Objectives</h2>
          <ul style="padding-left:24px;line-height:1.8;">
            ${structuredNotes.learningObjectives.map((obj) => `<li>${obj}</li>`).join("")}
          </ul>
        </div>
      `;
    }

    notes.forEach((h) => {
      html += `
        <div style="margin-bottom:24px;">
          <h2 style="font-size:18px;color:#1e293b;margin-bottom:8px;border-bottom:2px solid #e2e8f0;padding-bottom:8px;">
            ${h.title}
          </h2>
          <ul style="padding-left:24px;line-height:1.8;">
            ${h.keyPoints?.map((p) => `<li>${p}</li>`).join("") || ""}
          </ul>
      `;

      if (h.examples?.length > 0) {
        html += `
          <div style="margin-top:8px;background:#f1f5f9;padding:12px 16px;border-radius:6px;">
            <strong style="display:block;margin-bottom:4px;">💡 Examples:</strong>
            <ul style="padding-left:24px;margin:4px 0;line-height:1.6;">
              ${h.examples.map((ex) => `<li>${ex}</li>`).join("")}
            </ul>
          </div>
        `;
      }

      if (h.definitions?.length > 0) {
        html += `
          <div style="margin-top:8px;background:#f8fafc;padding:12px 16px;border-radius:6px;border:1px solid #e2e8f0;">
            <strong style="display:block;margin-bottom:4px;">📖 Key Terms:</strong>
            ${h.definitions
              .map(
                (d) => `
              <p style="margin:4px 0;"><strong>${d.term}:</strong> ${d.definition}</p>
            `,
              )
              .join("")}
          </div>
        `;
      }

      html += `</div>`;
    });

    if (structuredNotes.actionItems?.length > 0) {
      html += `
        <div style="margin-top:24px;padding:16px;background:#ecfdf5;border-radius:8px;border:1px solid #86efac;">
          <h2 style="font-size:18px;color:#059669;margin-bottom:8px;">✅ Action Items</h2>
          <ul style="padding-left:24px;line-height:1.8;">
            ${structuredNotes.actionItems.map((item) => `<li>${item}</li>`).join("")}
          </ul>
        </div>
      `;
    }

    if (structuredNotes.keyTerms?.length > 0) {
      html += `
        <div style="margin-top:24px;padding:16px;background:#f8fafc;border-radius:8px;border:1px solid #e2e8f0;">
          <h2 style="font-size:18px;color:#2563eb;margin-bottom:8px;">📖 Key Terms</h2>
          ${structuredNotes.keyTerms
            .map(
              (kt) => `
            <p style="margin:4px 0;"><strong>${kt.term}:</strong> ${kt.definition}</p>
          `,
            )
            .join("")}
        </div>
      `;
    }

    html += `
        <div style="margin-top:32px;padding-top:16px;border-top:2px solid #e2e8f0;text-align:center;color:#94a3b8;font-size:12px;">
          Generated by Recall - SDG 4: Quality Education
        </div>
      </div>
    `;

    return html;
  }

  // PDF Download Function
  const downloadPDF = async () => {
    if (!data) return;

    setIsDownloading(true);

    try {
      // Create temporary div for PDF content
      const tempDiv = document.createElement("div");
      tempDiv.style.position = "fixed";
      tempDiv.style.left = "-9999px";
      tempDiv.style.top = "0";
      tempDiv.style.width = "800px";
      tempDiv.style.background = "white";
      tempDiv.style.zIndex = "-1";
      tempDiv.innerHTML = buildPDFHTML(data);
      document.body.appendChild(tempDiv);

      // Wait for render
      await new Promise((resolve) => setTimeout(resolve, 300));

      // Generate PDF
      const opt = {
        margin: 10,
        filename: `${data.lecture.title || "lecture-notes"}.pdf`,
        image: { type: "jpeg", quality: 0.98 },
        html2canvas: {
          scale: 2,
          useCORS: true,
          backgroundColor: "#ffffff",
          logging: false,
        },
        jsPDF: {
          unit: "mm",
          format: "a4",
          orientation: "portrait",
        },
      };

      await html2pdf().set(opt).from(tempDiv).save();

      // Clean up
      document.body.removeChild(tempDiv);
    } catch (error) {
      console.error("PDF download failed:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsDownloading(false);
    }
  };

  if (!data) return <main className="loading-state">Loading workspace...</main>;

  const notes = data.lecture.structuredNotes?.headings || [];
  const structuredNotes = data.lecture.structuredNotes || {};

  return (
    <main className="lecture-workspace">
      <section className="notes-doc">
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            flexWrap: "wrap",
            gap: "12px",
          }}
        >
          <div>
            <p className="eyebrow">Structured Notes</p>
            <h1 className="truncate">{data.lecture.title}</h1>
          </div>
          <button
            onClick={downloadPDF}
            disabled={isDownloading}
            className="download-pdf-btn"
          >
            {isDownloading ? "⏳ Generating..." : "📄 Download PDF"}
          </button>
        </div>

        <div className="doc-meta">
          <span>{data.lecture.courseTag || "UNTAGGED"}</span>
          <span>
            {data.lecture.createdAt &&
              new Date(data.lecture.createdAt).toLocaleString()}
          </span>
        </div>

        {data.lecture.lectureContext && (
          <div className="context-note">
            <strong>Parser context</strong>
            <p>{data.lecture.lectureContext}</p>
          </div>
        )}

        {structuredNotes.summary && (
          <div className="context-note">
            <strong>📚 Summary</strong>
            <p>{structuredNotes.summary}</p>
          </div>
        )}

        {structuredNotes.learningObjectives?.length > 0 && (
          <article className="note-block">
            <h2>🎯 Learning Objectives</h2>
            <ul>
              {structuredNotes.learningObjectives.map((obj, i) => (
                <li key={i}>{obj}</li>
              ))}
            </ul>
          </article>
        )}

        {structuredNotes.actionItems?.length > 0 && (
          <article className="note-block">
            <h2>✅ Action Items</h2>
            <ul>
              {structuredNotes.actionItems.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
          </article>
        )}

        {notes.map((h, i) => (
          <article className="note-block" key={i}>
            <h2>{h.title}</h2>
            <ul>
              {h.keyPoints?.map((p, j) => (
                <li key={j}>{p}</li>
              ))}
            </ul>
            {h.examples?.length > 0 && (
              <blockquote>
                <strong>💡 Examples</strong>
                <ul style={{ marginTop: "4px", paddingLeft: "20px" }}>
                  {h.examples.map((ex, k) => (
                    <li key={k}>{ex}</li>
                  ))}
                </ul>
              </blockquote>
            )}
            {h.definitions?.length > 0 && (
              <div className="definition-list">
                <strong>📖 Key Terms</strong>
                {h.definitions.map((d, k) => (
                  <p key={k}>
                    <strong>{d.term}:</strong> {d.definition}
                  </p>
                ))}
              </div>
            )}
          </article>
        ))}

        {structuredNotes.keyTerms?.length > 0 && (
          <article
            className="note-block"
            style={{ borderTop: "2px solid #e2e8f0", paddingTop: "16px" }}
          >
            <h2>📖 Key Terms</h2>
            {structuredNotes.keyTerms.map((kt, i) => (
              <p key={i}>
                <strong>{kt.term}:</strong> {kt.definition}
              </p>
            ))}
          </article>
        )}
      </section>

      <aside className="ai-panel">
        <div className="ai-header">
          <p className="eyebrow">Personal AI</p>
          <h2>Chat Panel</h2>
        </div>

        <div className="chat-thread">
          {data.chatThread.messages.map((m, i) => (
            <div key={i} className={`message ${m.role}`}>
              <span>{m.role}</span>
              {m.role === "user" ? (
                <p>{m.content}</p>
              ) : (
                <ReactMarkdown>{m.content}</ReactMarkdown>
              )}
            </div>
          ))}
        </div>

        <form className="chat-input" onSubmit={ask}>
          <input
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="Ask a follow-up"
            required
          />
          <button disabled={!question.trim()}>Ask</button>
        </form>
      </aside>
    </main>
  );
}
